compact: false
directory:
  - ../
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
output: cli
quiet: false
skip-check:
  - CKV_TF_1 # "Ensure Terraform module sources use a commit hash"
  - CKV_GCP_83 # "Ensure PubSub Topics are encrypted with Customer Supplied Encryption Keys (CSEK)"
skip-fixes: false
skip-suppressions: false
soft-fail: false
