graph BT;
    var.owner-projecta-dev --> var.owner-projecta;
    var.owner-projecta-stage --> var.owner-projecta;
    var.owner-projecta-qa --> var.owner-projecta;
    var.owner-projecta-prodfix --> var.owner-projecta;
    var.owner-projecta-prod --> var.owner-projecta;
    var.owner-projecta-dr --> var.owner-projecta;
    var.owner-projectb-dev --> var.owner-projectb;
    var.owner-projectb-stage --> var.owner-projectb;
    var.owner-projectb-qa --> var.owner-projectb;
    var.owner-projectb-prodfix --> var.owner-projectb;
    var.owner-projectb-prod --> var.owner-projectb;
    var.owner-projectb-dr --> var.owner-projectb;
    var.owner-projectc-dev --> var.owner-projectc;
    var.owner-projectc-stage --> var.owner-projectc;
    var.owner-projectc-qa --> var.owner-projectc;
    var.owner-projectc-prodfix --> var.owner-projectc;
    var.owner-projectc-prod --> var.owner-projectc;
    var.owner-projectc-dr --> var.owner-projectc;
    var.owner-projecta --> module.folders.id[BussinesUnits];
    var.owner-projectb --> module.folders.id[BussinesUnits];
    var.owner-projectc --> module.folders.id[BussinesUnits];
