site_name: Secure Landing Zone in GCP
repo_url: https://github.com/Lapeyus/GCP-SLZ

nav:
  - Home: index.md
  - Secure Landing Zone:
      - The Seed Project: seed.md
      - Folders Core: slz-folders-core.md
      - Groups: slz-groups.md
      - IAM Groups: slz-groups-iam.md
      - Organizational Policies: slz-org-policy.md
      - Billing Projects: slz-projects-billing.md
      - CI/CD Projects: slz-projects-cicd.md
      - Shared VPC Projects: slz-projects-sharedvpc.md
      - L&M: slz-projects-log-monitor.md
      - Terraform State Buckets: tfstate-buckets.md
      - FAQs: slz-faqs.md
  - Bussiness Unit Configurations:
      - Folders: bu-folders.md
      - Groups: bu-groups.md
      - Projects: bu-projects.md
      - FAQs: bu-faqs.md
  - additional-resources.md
theme:
  name: 'material' # mkdocs, readthedocs material
  language: en
  logo: img/logo.png
  favicon: img/logo.png
  font:
    text: Roboto
  # icon:
  #   repo: fontawesome/brands/git-alt 
    
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate 

  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - macros
 
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
#   - codehilite
#   - pymdownx.betterem
