site_name: Secure Landing Zone in GCP
repo_url: https://github.com/66degrees/devops-ve-pod-1-slz

nav:
  - Home: index.md
  - Secure Landing Zone Core:
      - The Seed Project: seed.md
      - Folders Core: slz-folders-core.md
      - Groups: slz-groups.md
      - Groups IAM: slz-groups-iam.md
      - Organizational Policies: slz-org-policy.md
      - Billing Projects: slz-projects-billing.md
      - CI/CD Projects: slz-projects-cicd.md
      - Shared VPC Projects: slz-projects-sharedvpc.md
      - L&M: slz-projects-log-monitor.md
      - Terraform State Buckets: tfstate-buckets.md
      - FAQs: slz-faqs.md
  - Bussiness Unit Configurations:
      - Folders: bu-folders.md
      - Groups: bu-groups.md
      - Projects: bu-projects.md
      - FAQs: bu-faqs.md
  - Terraform Docs: tfdocs.md
  - Additional Resources:
      - Articles: additional-resources.md

theme:
  name: 'material' # mkdocs, readthedocs material
  language: en
  logo: img/logo.png
  favicon: img/logo.png
  font:
    text: Roboto
  # icon:
  #   repo: fontawesome/brands/git-alt

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode


plugins:
  - diagrams:
      file_extension: ".diagrams.py"
      max_workers: 5
  - search
  - macros

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - mkdocs_graphviz:
        light_theme: 000000
        dark_theme: FFFFFF
        color: 789ABC
        bgcolor: none
        graph_color: 789ABC
        graph_fontcolor: 789ABC
        node_color: 789ABC
        node_fontcolor: 050709
        edge_color: 789ABC
        edge_fontcolor: 789ABC
        priority: 75
  - tables
#   - codehilite
#   - pymdownx.betterem

# extra_javascript:
#   - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
